# Deployment workflow - build and redeploy website on pushes to repo
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      # add config
      - name: Config
        run: |
          git config --local user.email "audaris@gmail.com"
          git config --local user.name "ablades"
    # Build Website
      - name: Build
        run: |
          npm install
          npm run deploy